### ISSUE TITLE
{"success":false,"error":"Your phone number was not provided in E.164 format, or free SMS are disabled for this country"}

### ISSUE THREAD

**Issue by naresh1807** [Sanif007/sms-scammer#4]
{"success":false,"error":"Your phone number was not provided in E.164 format, or free SMS are disabled for this country"}

**Comment by ayushjain150** [comment]
I am facing the same issue...!!!

* For reference :- *
* I am using an Indian number here *
* Format :- +910000000000 *

**Comment by Sanif007** [comment]
Sorry to inform you guys but api which i was using is not letting free sms in some countries!  Am trying to use some other api!  Till then you can buy sms from textbelt website and add in code to use it again or please wait!

**Comment by Addie2008** [comment]
i am also facing success":false,"error":"Your phone number was not provided in E.164 format, or free SMS are disabled for this country"}this what to do i cant understand

**Comment by Sanif007** [comment]
This is because api code has blocked some countries for trial sms usage!
Please forgive me for inconvenience! If you find other similar api then
please inform me too I'll be glad to listen and improve! ~Ninjahydra

**Comment by Egolka1** [comment]
I have this error too

**Comment by Agnirajawat** [comment]
facing same problem please help us

**Comment by Egolka1** [comment]
I didn't find a solution for this problem


чт, 24 мар. 2022 г., 17:24 Agnirajawat ***@***.***>:

**Comment by Sanif007** [comment]
You can solve this issue only by purchasing api. Sorry for that.. 
[Click here to purchase ](https://textbelt.com/purchase/?generateKey=1)

**Comment by hariprasad0511** [comment]
Please mention this issue in the readme and while executing the repo so that users will not execute this repo.
Thanks

**Comment by Sanif007** [comment]
> Please mention this issue in the readme and while executing the repo so that users will not execute this repo. Thanks

Thanks sir i am not so good in this but thanks. I'll mention it ASAP. 😇🤗

**Comment by efremjon** [comment]
some problem pls try to solive it

**Comment by shriyansh01010** [comment]
Please Solve it :|

**Comment by ElPincheChucky** [comment]
someone solved?

**Comment by Mr7Robot578** [comment]
no i cant solved it

**Comment by Raziel1981** [comment]
Enfrentando mesmo problema

**Comment by Atulkumar112** [comment]
Why it's banned in india guys?

**Comment by Priscilla544** [comment]
Why can't u buy the sms using momo money na
