### ISSUE TITLE
Message not going

### ISSUE THREAD

**Issue by Ridwanijaola** [Sanif007/sms-scammer#6]
{"success":false,"error":"Your phone number was not provided in E.164 format, or free SMS are disabled for this country"}

This is what is showing

**Comment by ghdd342** [comment]
git clone https://github.com/Sanif007/sms-scammer

**Comment by N00bhac** [comment]
Error

**Comment by Sanif007** [comment]
Buy api bro.. website blocked free sms in some countries... Sorry for that [click here to buy api](https://textbelt.com/purchase/?generateKey=1)
